version: "3.5"
services:
  data:
    build: ../sl-data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: yarn start
    networks:
      - local_graphcool
    environment:
      GRAPHCOOL_HOST: localfaas
  lambda:
      build: ../sl-lambda
      command: yarn start
      networks:
      - local_graphcool
      ports:
        - '5464:5464'

networks:
  local_graphcool:
    name: local_graphcool
    driver: bridge
