version: "3.5"
services:
  data:
    volumes:
      - ../sl-data:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
  lambda:
      volumes:
        - ../sl-lambda:/app
        - /app/node_modules
