version: '3.5'
services:
  server:
    build: ../sl-server
    ports:
        - '4332:4332'
    depends_on:
      - data
  data:
    build: ../sl-data
    command: sh -c './wait-for -t 180 prisma:4466 -- yarn start'
    depends_on:
      - prisma
  prisma:
    image: prismagraphql/prisma:1.10
    restart: always
    ports:
    - "4466:4466"
    depends_on:
      - postgres
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
  lambda:
      build: ../sl-lambda
      command: yarn start
      ports:
        - '5464:5464'
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
