# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    working_directory: /app
    docker:
       - image: docker:18.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install CircleCI dependencies
          command: |
            apk add --no-cache curl curl-dev py-pip
            pip install --upgrade pip
            pip install docker-compose
      - run:
          name: Move repo into subfolder
          command: |
            cp -r /app/. ~/sl-base
            mv -v ~/sl-server /app/sl-base
      - run:
          name: Get sl-* dependencies
          command: ./sl-base/init.sh
      - run:
          name: Build Docker images
          command: docker-compose -f ./sl-base/docker-compose.yml build
      - run:
           name: Start Docker
           command: docker-compose -f ./sl-base/docker-compose.yml up -d
